runtime: python311
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2  # Adjust instance size as needed

env_variables:
  DB_USER: "root"
  DB_PASS: "6304G.Vik@s"
  DB_NAME: "voter_registration"
  INSTANCE_CONNECTION_NAME: "voter-application-454807:asia-south2:voting-system-db"

beta_settings:
  cloud_sql_instances: "voter-application-454807:asia-south2:voting-system-db"
