runtime: python39
entrypoint: python main.py

instance_class: F2  # Specifies the instance size (adjust as needed)

# Cloud SQL Configuration
beta_settings:
  cloud_sql_instances: voter-application-454807:asia-south2:voting-system-db